import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/providers/theme-provider";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={font.className}>
        <main className="h-full">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />

            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
